# Generated by Django 4.0.7 on 2023-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True)),
                ('duration', models.CharField(max_length=15)),
                ('release_date', models.PositiveSmallIntegerField()),
                ('budget', models.IntegerField()),
                ('synopsis', models.TextField(max_length=1000)),
            ],
        ),
    ]
