# Generated by Django 4.0.7 on 2023-07-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'release_date')},
        ),
    ]
